/*
 * Copyright (C) 2022 Stefan Todorovic <orthybt@gmail.com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package gui;

import XML_Wrappers.OrthyPaths;
import XML_Wrappers.OrthyPoints;
import cloud.Cloud;
import dataObjects.Patient;
import handlers.PointHandler;

import javax.swing.*;
import java.io.File;
import java.nio.file.Path;

/**
 *
 * @author Stefan Todorovic <orthybt@gmail.com>
 */
public class gui extends javax.swing.JFrame {
    
    private Cloud c;
    public gui() {
        initComponents();
        //initialize everything here, and good luck :)
        this.c = new Cloud();
        initLateral();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionPane = new javax.swing.JOptionPane();
        desktop = new javax.swing.JDesktopPane();
        lateralPane = new javax.swing.JTabbedPane();
        maintPanel_Lateral = new javax.swing.JPanel();
        layeredPanel = new javax.swing.JLayeredPane();
        imagePanel_Lateral = new javax.swing.JPanel();
        imageLabel_Lateral = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ch1 = new javax.swing.JCheckBox();
        ch2 = new javax.swing.JCheckBox();
        ch4 = new javax.swing.JCheckBox();
        ch3 = new javax.swing.JCheckBox();
        ch5 = new javax.swing.JCheckBox();
        ch6 = new javax.swing.JCheckBox();
        ch7 = new javax.swing.JCheckBox();
        ch8 = new javax.swing.JCheckBox();
        ch9 = new javax.swing.JCheckBox();
        ch10 = new javax.swing.JCheckBox();
        ch11_ = new javax.swing.JCheckBox();
        ch12 = new javax.swing.JCheckBox();
        ch13 = new javax.swing.JCheckBox();
        ch14 = new javax.swing.JCheckBox();
        ch15 = new javax.swing.JCheckBox();
        ch16 = new javax.swing.JCheckBox();
        jButton9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        tx1 = new javax.swing.JTextField();
        lab1 = new javax.swing.JLabel();
        tx2 = new javax.swing.JTextField();
        lab7 = new javax.swing.JLabel();
        button_JPF = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lab2 = new javax.swing.JLabel();
        tx3 = new javax.swing.JTextField();
        tx4 = new javax.swing.JTextField();
        lab8 = new javax.swing.JLabel();
        lab9 = new javax.swing.JLabel();
        tx5 = new javax.swing.JTextField();
        button_ELine = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        tx6 = new javax.swing.JTextField();
        lab3 = new javax.swing.JLabel();
        lab10 = new javax.swing.JLabel();
        lab11 = new javax.swing.JLabel();
        lab12 = new javax.swing.JLabel();
        button_ZAngle = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        tx7 = new javax.swing.JTextField();
        lab4 = new javax.swing.JLabel();
        lab13 = new javax.swing.JLabel();
        button_FacialConvexity = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        tx8 = new javax.swing.JTextField();
        lab14 = new javax.swing.JLabel();
        lab15 = new javax.swing.JLabel();
        button_NasoLabialAngle = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        tx9 = new javax.swing.JTextField();
        lab6 = new javax.swing.JLabel();
        lab16 = new javax.swing.JLabel();
        button_MentoLabialAngle = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        patientInfoPanel_Lateral = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txLastName_lateral = new javax.swing.JTextField();
        txfirstName_lateral = new javax.swing.JTextField();
        txId_lateral = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        frontalLines19 = new javax.swing.JButton();
        frontalLines20 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        frontalLines18 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        frontalLines17 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        welcome = new javax.swing.JInternalFrame();
        jPanel12 = new javax.swing.JPanel();
        buttonOption_start1 = new javax.swing.JButton();
        buttonOption_start2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("main_frame");
        setName("mainFrame"); // NOI18N

        desktop.setBackground(new java.awt.Color(240, 240, 240));
        desktop.setForeground(new java.awt.Color(240, 240, 240));

        lateralPane.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lateralPaneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lateralPaneFocusLost(evt);
            }
        });

        maintPanel_Lateral.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        maintPanel_Lateral.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                maintPanel_LateralFocusLost(evt);
            }
        });

        layeredPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout imagePanel_LateralLayout = new javax.swing.GroupLayout(imagePanel_Lateral);
        imagePanel_Lateral.setLayout(imagePanel_LateralLayout);
        imagePanel_LateralLayout.setHorizontalGroup(
            imagePanel_LateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );
        imagePanel_LateralLayout.setVerticalGroup(
            imagePanel_LateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
        );

        layeredPanel.setLayer(imagePanel_Lateral, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredPanel.setLayer(imageLabel_Lateral, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layeredPanelLayout = new javax.swing.GroupLayout(layeredPanel);
        layeredPanel.setLayout(layeredPanelLayout);
        layeredPanelLayout.setHorizontalGroup(
            layeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
            .addGroup(layeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layeredPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(imagePanel_Lateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layeredPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(imageLabel_Lateral, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layeredPanelLayout.setVerticalGroup(
            layeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(layeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layeredPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(imagePanel_Lateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layeredPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(imageLabel_Lateral, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ch1.setText("cal1");
        ch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch1ActionPerformed(evt);
            }
        });

        ch2.setText("cal 2");
        ch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch2ActionPerformed(evt);
            }
        });

        ch4.setText("Or");
        ch4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch4ActionPerformed(evt);
            }
        });

        ch3.setText("Po");
        ch3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch3ActionPerformed(evt);
            }
        });

        ch5.setText("Gl");
        ch5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch5ActionPerformed(evt);
            }
        });

        ch6.setText("N");
        ch6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch6ActionPerformed(evt);
            }
        });

        ch7.setText("Pn");
        ch7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch7ActionPerformed(evt);
            }
        });

        ch8.setText("Col");
        ch8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch8ActionPerformed(evt);
            }
        });

        ch9.setText("Sn");
        ch9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch9ActionPerformed(evt);
            }
        });

        ch10.setText("Ala");
        ch10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch10ActionPerformed(evt);
            }
        });

        ch11_.setText("Ls");
        ch11_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch11_ActionPerformed(evt);
            }
        });

        ch12.setText("Sto");
        ch12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch12ActionPerformed(evt);
            }
        });

        ch13.setText("Li");
        ch13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch13ActionPerformed(evt);
            }
        });

        ch14.setText("Sm");
        ch14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch14ActionPerformed(evt);
            }
        });

        ch15.setText("Pog");
        ch15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch15ActionPerformed(evt);
            }
        });

        ch16.setText("Gn");
        ch16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch16ActionPerformed(evt);
            }
        });

        jButton9.setText("undo");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9)
                    .addComponent(ch8)
                    .addComponent(ch9)
                    .addComponent(ch10)
                    .addComponent(ch11_)
                    .addComponent(ch12)
                    .addComponent(ch13)
                    .addComponent(ch14)
                    .addComponent(ch15)
                    .addComponent(ch16)
                    .addComponent(ch1)
                    .addComponent(ch2)
                    .addComponent(ch4)
                    .addComponent(ch3)
                    .addComponent(ch5)
                    .addComponent(ch6)
                    .addComponent(ch7))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ch1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ch2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ch3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ch4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ch5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ch6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ch7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ch8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ch9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ch10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ch11_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ch12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ch13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ch14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ch15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ch16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jaw profile field", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 18))); // NOI18N

        tx1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lab1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lab1.setText("Maxilla/Pn");
        lab1.setOpaque(true);

        tx2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lab7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lab7.setText("Mandible/Maxilla");
        lab7.setOpaque(true);

        button_JPF.setText("Show/Hide");
        button_JPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_JPFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tx1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(button_JPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tx2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_JPF))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rickets E-Line", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 18))); // NOI18N

        lab2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lab2.setText("Upper lip to E-Line");
        lab2.setOpaque(true);

        tx3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tx3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx3ActionPerformed(evt);
            }
        });

        tx4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tx4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx4ActionPerformed(evt);
            }
        });

        lab8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lab8.setText("Lower lip to E-Line");
        lab8.setOpaque(true);

        lab9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lab9.setText("Upper to Lower lip");
        lab9.setOpaque(true);

        tx5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tx5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx5ActionPerformed(evt);
            }
        });

        button_ELine.setText("Show/Hide");
        button_ELine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ELineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tx4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(button_ELine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tx5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tx5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_ELine))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Merrifield Z angle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 18))); // NOI18N

        tx6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tx6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx6ActionPerformed(evt);
            }
        });

        lab3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lab3.setText("Average");
        lab3.setOpaque(true);

        lab10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lab10.setText("70 - 81");
        lab10.setOpaque(true);

        lab11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lab11.setText("75 - 79");
        lab11.setOpaque(true);

        lab12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lab12.setText("Ideal");
        lab12.setOpaque(true);

        button_ZAngle.setText("Show/Hide");
        button_ZAngle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ZAngleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lab3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lab10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lab12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lab11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tx6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_ZAngle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_ZAngle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Facial Convexity", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 18))); // NOI18N

        tx7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lab4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lab4.setText("Average");
        lab4.setOpaque(true);

        lab13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lab13.setText("8 - 16");
        lab13.setOpaque(true);

        button_FacialConvexity.setText("Show/Hide");
        button_FacialConvexity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_FacialConvexityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lab4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lab13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_FacialConvexity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lab4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lab13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tx7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_FacialConvexity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nasolabial Angle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 18))); // NOI18N

        tx8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lab14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lab14.setText("Men - 90 -95");
        lab14.setOpaque(true);

        lab15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lab15.setText("Women - 95 - 105");
        lab15.setOpaque(true);

        button_NasoLabialAngle.setText("Show/Hide");
        button_NasoLabialAngle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_NasoLabialAngleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab14)
                    .addComponent(lab15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_NasoLabialAngle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tx8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_NasoLabialAngle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mentolabial Angle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 18))); // NOI18N

        tx9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lab6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lab6.setText("Average");
        lab6.setOpaque(true);

        lab16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lab16.setText("108 - 118");
        lab16.setOpaque(true);

        button_MentoLabialAngle.setText("Show/Hide");
        button_MentoLabialAngle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_MentoLabialAngleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lab6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lab16, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_MentoLabialAngle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(tx9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_MentoLabialAngle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lab6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton13.setText("Reset Analysis");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton13)
                .addGap(45, 45, 45))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        patientInfoPanel_Lateral.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 18))); // NOI18N

        jButton1.setText("New Patient");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txLastName_lateral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txLastName_lateralActionPerformed(evt);
            }
        });

        txfirstName_lateral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfirstName_lateralActionPerformed(evt);
            }
        });

        jLabel3.setText("Last Name");

        jLabel1.setText("ID");

        jLabel2.setText("First Name");

        frontalLines19.setText("Save Patient");
        frontalLines19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frontalLines19ActionPerformed(evt);
            }
        });

        frontalLines20.setText("Load Patient");
        frontalLines20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frontalLines20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout patientInfoPanel_LateralLayout = new javax.swing.GroupLayout(patientInfoPanel_Lateral);
        patientInfoPanel_Lateral.setLayout(patientInfoPanel_LateralLayout);
        patientInfoPanel_LateralLayout.setHorizontalGroup(
            patientInfoPanel_LateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientInfoPanel_LateralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patientInfoPanel_LateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(patientInfoPanel_LateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(frontalLines20, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(frontalLines19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txfirstName_lateral)
                    .addComponent(txLastName_lateral)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txId_lateral))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        patientInfoPanel_LateralLayout.setVerticalGroup(
            patientInfoPanel_LateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientInfoPanel_LateralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patientInfoPanel_LateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patientInfoPanel_LateralLayout.createSequentialGroup()
                        .addComponent(txId_lateral, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfirstName_lateral, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txLastName_lateral, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(patientInfoPanel_LateralLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frontalLines19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frontalLines20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        frontalLines18.setText("Select Image");
        frontalLines18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frontalLines18ActionPerformed(evt);
            }
        });
        jToolBar1.add(frontalLines18);

        jButton12.setText("Points");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton12);

        frontalLines17.setText("Lines");
        frontalLines17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frontalLines17ActionPerformed(evt);
            }
        });
        jToolBar1.add(frontalLines17);

        jButton11.setText("Measure");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton11);

        jButton10.setText("Reset Lateral");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton10);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addComponent(patientInfoPanel_Lateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientInfoPanel_Lateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(574, 574, 574))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout maintPanel_LateralLayout = new javax.swing.GroupLayout(maintPanel_Lateral);
        maintPanel_Lateral.setLayout(maintPanel_LateralLayout);
        maintPanel_LateralLayout.setHorizontalGroup(
            maintPanel_LateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintPanel_LateralLayout.createSequentialGroup()
                .addGroup(maintPanel_LateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(maintPanel_LateralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(layeredPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        maintPanel_LateralLayout.setVerticalGroup(
            maintPanel_LateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, maintPanel_LateralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maintPanel_LateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(layeredPanel)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, maintPanel_LateralLayout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        lateralPane.addTab("Lateral Photo Analysis", maintPanel_Lateral);

        welcome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        welcome.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        welcome.setMaximizable(true);
        welcome.setResizable(true);
        welcome.setVisible(true);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Welcome to ORTHY", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 18))); // NOI18N

        buttonOption_start1.setText("New Patient");
        buttonOption_start1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOption_start1ActionPerformed(evt);
            }
        });

        buttonOption_start2.setText("Free flow");
        buttonOption_start2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOption_start2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonOption_start1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonOption_start2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOption_start1)
                    .addComponent(buttonOption_start2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout welcomeLayout = new javax.swing.GroupLayout(welcome.getContentPane());
        welcome.getContentPane().setLayout(welcomeLayout);
        welcomeLayout.setHorizontalGroup(
            welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        welcomeLayout.setVerticalGroup(
            welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        desktop.setLayer(lateralPane, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(welcome, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lateralPane)
                .addContainerGap())
            .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopLayout.createSequentialGroup()
                    .addGap(718, 718, 718)
                    .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(718, Short.MAX_VALUE)))
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lateralPane)
                .addContainerGap())
            .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopLayout.createSequentialGroup()
                    .addGap(405, 405, 405)
                    .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(406, Short.MAX_VALUE)))
        );

        lateralPane.getAccessibleContext().setAccessibleName("");

        jMenu1.setText("File");

        jMenuItem1.setText("Load Patients");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lateralPaneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lateralPaneFocusLost

    }//GEN-LAST:event_lateralPaneFocusLost

    private void lateralPaneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lateralPaneFocusGained

    }//GEN-LAST:event_lateralPaneFocusGained

    private void maintPanel_LateralFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_maintPanel_LateralFocusLost
        imagePanel_Lateral.addMouseListener(getC().pointHandler());
    }//GEN-LAST:event_maintPanel_LateralFocusLost

    private void ch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch1ActionPerformed

    private void ch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch2ActionPerformed

    private void ch4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch4ActionPerformed

    private void ch3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch3ActionPerformed

    private void ch5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch5ActionPerformed

    private void ch6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch6ActionPerformed

    private void ch7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch7ActionPerformed

    private void ch8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch8ActionPerformed

    private void ch9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch9ActionPerformed

    private void ch10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch10ActionPerformed

    private void ch11_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch11_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch11_ActionPerformed

    private void ch12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch12ActionPerformed

    private void ch13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch13ActionPerformed

    private void ch14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch14ActionPerformed

    private void ch15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch15ActionPerformed

    private void tx6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx6ActionPerformed

    private void tx3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx3ActionPerformed

    private void ch16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch16ActionPerformed

    private void tx4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx4ActionPerformed

    private void tx5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx5ActionPerformed

    private void txfirstName_lateralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfirstName_lateralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfirstName_lateralActionPerformed

    private void txLastName_lateralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txLastName_lateralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txLastName_lateralActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        undoPoint();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        hardReset_Lateral();
        initLateral();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        initResults();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void frontalLines17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frontalLines17ActionPerformed
        initLines();
    }//GEN-LAST:event_frontalLines17ActionPerformed

    private void frontalLines18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frontalLines18ActionPerformed
        selectFile();
    }//GEN-LAST:event_frontalLines18ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        selectPoints();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void frontalLines19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frontalLines19ActionPerformed
        savePatient();
    }//GEN-LAST:event_frontalLines19ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        createPatient();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void frontalLines20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frontalLines20ActionPerformed
        loadPatient();
    }//GEN-LAST:event_frontalLines20ActionPerformed

    private void button_JPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_JPFActionPerformed
        boolean showLines = true;
        if (showLines || button_JPF.isSelected()) {
            c.guiHandler().clearImagePanel_Lateral();
            //c.lineHandler().drawJawProfileField();
            showLines = false;
        }
        if(!showLines && button_JPF.isSelected()) {
            c.lineHandler().drawJawProfileField();
            showLines = true;
        }
    }//GEN-LAST:event_button_JPFActionPerformed

    private void button_FacialConvexityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_FacialConvexityActionPerformed
        boolean showLines = true;
        if (showLines || button_FacialConvexity.isSelected()) {
            c.guiHandler().clearImagePanel_Lateral();
            showLines = false;
        }
        if(!showLines && button_FacialConvexity.isSelected()) {
            c.lineHandler().drawFacialConvexity();
            showLines = true;
        }
    }//GEN-LAST:event_button_FacialConvexityActionPerformed

    private void button_MentoLabialAngleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_MentoLabialAngleActionPerformed
        boolean showLines = true;
        if (showLines || button_MentoLabialAngle.isSelected()) {
            c.guiHandler().clearImagePanel_Lateral();
            showLines = false;
        }
        if(!showLines && button_MentoLabialAngle.isSelected()) {
            c.lineHandler().drawMentolabialAngle();
            showLines = true;
        }
    }//GEN-LAST:event_button_MentoLabialAngleActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        softReset_Lateral();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void buttonOption_start1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOption_start1ActionPerformed
        initLateral();
        welcome.setVisible(false);
        welcome.toBack();
    }//GEN-LAST:event_buttonOption_start1ActionPerformed

    private void buttonOption_start2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOption_start2ActionPerformed
        initLateral();
        createTestPatient();
        welcome.setVisible(false);
        welcome.toBack();
        //lateralPane.setVisible(true);
    }//GEN-LAST:event_buttonOption_start2ActionPerformed

    private void button_ELineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ELineActionPerformed
        boolean showLines = true;
        if (showLines && button_ELine.isSelected()) {
            c.guiHandler().clearImagePanel_Lateral();
            showLines = false;
        }
        if(!showLines && button_ELine.isSelected()) {
            c.lineHandler().drawELine();
            showLines = true;
        }
    }//GEN-LAST:event_button_ELineActionPerformed

    private void button_ZAngleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ZAngleActionPerformed
        boolean showLines = true;
        if (showLines || button_ZAngle.isSelected()) {
            c.guiHandler().clearImagePanel_Lateral();
            showLines = false;
        }
        if(!showLines && button_ZAngle.isSelected()) {
            c.lineHandler().drawZLine();
            showLines = true;
        }
    }//GEN-LAST:event_button_ZAngleActionPerformed

    private void button_NasoLabialAngleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_NasoLabialAngleActionPerformed
        boolean showLines = true;
        if (showLines || button_NasoLabialAngle.isSelected()) {
            c.guiHandler().clearImagePanel_Lateral();
            showLines = false;
        }
        if(!showLines && button_NasoLabialAngle.isSelected()) {
            c.lineHandler().drawNasolabialAngle();
            showLines = true;
        }
    }//GEN-LAST:event_button_NasoLabialAngleActionPerformed
    //************************************************************************\\
    //                          MY METHODS                                    \\
    //************************************************************************\\

    //************************************************************************\\
    //                          GUI COMPONENTS - IMAGE - INIT                 \\
    //************************************************************************\\
    private void initImageLabel(){
        getC().gc().setImageLabelLateral(imageLabel_Lateral);
    }
    private void initImagePanel(){
        //LateralPhoto imagePanel
        getC().gc().setImagePanelLateral(imagePanel_Lateral);
    }
    private void initLayeredPanel(){
        layeredPanel.setComponentZOrder(imagePanel_Lateral, 0);//load the image at 0
        layeredPanel.setComponentZOrder(imagePanel_Lateral, 1);//draw at 1
    }
    private void initImageGui(){
        initImagePanel();
        initImageLabel();
        initLayeredPanel();
    }
    //************************************************************************\\
    //                          GUI COMPONENTS - PATIENT - INIT                      \\
    //************************************************************************\\
    private void initPatientGui(){
        getC().gc().setTxId_lateral(txId_lateral);
        getC().gc().setTxFirstName_lateral(txfirstName_lateral);
        getC().gc().setTxLastName_lateral(txLastName_lateral);
    }
    //************************************************************************\\
    //                          GUI COMPONENTS - OUTPUT - INIT                       \\
    //************************************************************************\\
    private void initCheckBoxes_Lateral(){
        //LateralPhoto checkBoxes
        getC().gc().setCh1(ch1);
        getC().gc().setCh2(ch2);
        getC().gc().setCh3(ch3);
        getC().gc().setCh4(ch4);
        getC().gc().setCh5(ch5);
        getC().gc().setCh6(ch6);
        getC().gc().setCh7(ch7);
        getC().gc().setCh8(ch8);
        getC().gc().setCh9(ch9);
        getC().gc().setCh10(ch10);
        getC().gc().setCh11(ch11_);
        getC().gc().setCh12(ch12);
        getC().gc().setCh13(ch13);
        getC().gc().setCh14(ch14);
        getC().gc().setCh15(ch15);
        getC().gc().setCh16(ch16);
        //Lateral Array
        getC().gc().initCheckBoxes_Lateral();
    }
    private void initTxtFields(){
        //LateralPhoto txtFields
        getC().gc().setTx1(tx1);
        getC().gc().setTx2(tx2);
        getC().gc().setTx3(tx3);
        getC().gc().setTx4(tx4);
        getC().gc().setTx5(tx5);
        getC().gc().setTx6(tx6);
        getC().gc().setTx7(tx7);
        getC().gc().setTx8(tx8);
        getC().gc().setTx9(tx9);
        getC().gc().setTxId_lateral(txId_lateral);
        getC().gc().setTxFirstName_lateral(txfirstName_lateral);
        getC().gc().setTxLastName_lateral(txLastName_lateral);
    }
    private void initLabels(){
        /**
        c.gc().setLab1(lab1);
        c.gc().setLab2(lab2);
        c.gc().setLab3(lab3);
        c.gc().setLab4(lab4);
        //c.gc().setLab5(null);
        c.gc().setLab6(lab6);
        * */
    }
    private void initOutputGui(){
        initCheckBoxes_Lateral();
        initTxtFields();
        initLabels();
    }
    //************************************************************************\\
    //                          METHODS - PATIENT                             \\
    //************************************************************************\\
    private void createPatient(){
        c.dataManager().createPatient(  
                                        txId_lateral.getText(), 
                                        txfirstName_lateral.getText(), 
                                        txLastName_lateral.getText(),
                                        new OrthyPoints(), 
                                        new OrthyPaths());
    }
    private void createTestPatient(){
        getC().dataManager().createPatient("1", "DEMO", "DEMO");
    }
    //************************************************************************\\
    //                          METHODS - IMAGE                               \\
    //************************************************************************\\
    private void selectFile(){
        JFileChooser fileChooser = new JFileChooser();
        //DEFAULT DIRECTORY 
        fileChooser.setCurrentDirectory(
                                c.pathHandler().getRootDir().toFile());
        int returnVal = fileChooser.showOpenDialog(imagePanel_Lateral); 
        if(returnVal == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            //IMAGE INIT
            c.imageHandler().initImage(imageLabel_Lateral, file);
            //PATIENT UPDATE
            Patient currentPatient = c.data().getCurrentPatient();
            //PATHS ARE UPDATED HERE           
           c.pathHandler().initPatientPaths(file, currentPatient);
        }
    }
    private void initImage(File file, JLabel label){
        getC().imageHandler().initImage(label, file);
    }
    //************************************************************************\\
    //                          METHODS - CANVAS                              \\
    //************************************************************************\\
    private void selectPoints(){
        PointHandler pointHandler = c.pointHandler();
        imagePanel_Lateral.addMouseListener(pointHandler);
        //imageLabel_Lateral.removeMouseListener(pointHandler);
    }
    private void clearCanvas(){
        c.guiHandler().clearCanvas_Lateral();
    }
    //************************************************************************\\
    //                          METHODS - LINES                               \\
    //************************************************************************\\
    private void initLines(){
        getC().lineHandler().initLines();
        getC().lineHandler().drawLines();
    }
    //************************************************************************\\
    //                          METHODS - RESULTS                             \\
    //************************************************************************\\
    private void initResults(){
        getC().resultHandler().initResults_Lateral();
    }
    //************************************************************************\\
    //                          METHODS - SAVE PATIENT                        \\
    //************************************************************************\\
    public void savePatient(){
        c.dataManager().savePatient(c.data().getCurrentPatient());
    }
    //************************************************************************\\
    //                          METHODS - SAVE PATIENTS                        \\
    //************************************************************************\\
    public void savePatients(){
        //THE PATIENTS ARE UPDATED AT EACH STEP OF THE PROGRAM
        //THE HANDLERS ARE RESPONSIBLE FOR CALLING PATIENT UPDATE
        c.dataManager().savePatients(c.data().getPatients());
    }
    //************************************************************************\\
    //                          METHODS - LOAD PATIENT                        \\
    //************************************************************************\\
    public void selectFile_Load(){
        JFileChooser fileChooser = new JFileChooser();
        //DEFAULT DIRECTORY 
        fileChooser.setCurrentDirectory(
                                c.pathHandler().getRootDir().toFile());
        int returnVal = fileChooser.showOpenDialog(imagePanel_Lateral); 
        if(returnVal == JFileChooser.APPROVE_OPTION){
            File xmlFile = fileChooser.getSelectedFile();
            Patient currentPatient = c.data().getCurrentPatient();
            c.dataManager().loadPatient(xmlFile);
            //IMAGE INIT
            Path imgPath = c.data().getCurrentPatient().getImagePath();
            c.imageHandler().initImage(imageLabel_Lateral, imgPath.toFile());
            //NO UPDATES ARE REQUIRED SINCE THIS A LOAD FUNCTION
        }
    }
    public void loadPatient(){
        JFileChooser fileChooser = new JFileChooser();
        //DEFAULT DIRECTORY 
        fileChooser.setCurrentDirectory(
                                c.pathHandler().getRootDir().toFile());
        int returnVal = fileChooser.showOpenDialog(imagePanel_Lateral); 
        if(returnVal == JFileChooser.APPROVE_OPTION){
            File xmlFile = fileChooser.getSelectedFile();
            //PATIENTS INIT     
            c.dataManager().loadPatient(xmlFile);
            //IMAGE INIT
            Path imgPath = c.data().getCurrentPatient().getImagePath();
            c.imageHandler().initImage(imageLabel_Lateral, imgPath.toFile());
            //NO UPDATES ARE REQUIRED SINCE THIS A LOAD FUNCTION
            
        }
    }
    //************************************************************************\\
    //                          METHODS - RESET LATERAL                       \\
    //************************************************************************\\
    public void hardReset_Lateral(){
        c.pointHandler().resetPoints();
        c.lineHandler().resetLines();
        c.guiHandler().hardReset_Lateral();
        c.data().hardReset();
        imagePanel_Lateral.removeMouseListener(c.pointHandler());
    }
    public void softReset_Lateral(){
        c.pointHandler().resetPoints();
        c.guiHandler().softReset_Lateral();
        imagePanel_Lateral.removeMouseListener(c.pointHandler());
        //selectPoints();
    }
    //************************************************************************\\
    //                          METHODS - MISC                                \\
    //************************************************************************\\
    public void undoPoint(){
        getC().pointHandler().undoPoint();
    }
    //************************************************************************\\
    //                          INIT                                          \\
    //************************************************************************\\
    public void initLateral(){
        
        initPatientGui();
        initImageGui();
        initOutputGui();
        c.initialize();// PERFECT :*** GOOD JOB :)))
        intro();
    }
    public void intro(){
       this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
       welcome.toFront();
       welcome.setClosable(true);
       welcome.setVisible(true);
        if (buttonOption_start1.isSelected() || buttonOption_start2.isSelected()) {
            //c.guiHandler().disable_tx_PatientInputFields();
            welcome.setVisible(false);
            welcome.toBack();
        }
            
    }
    //************************************************************************\\
    //                          END                                   
    //************************************************************************\\
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOption_start1;
    private javax.swing.JButton buttonOption_start2;
    private javax.swing.JButton button_ELine;
    private javax.swing.JButton button_FacialConvexity;
    private javax.swing.JButton button_JPF;
    private javax.swing.JButton button_MentoLabialAngle;
    private javax.swing.JButton button_NasoLabialAngle;
    private javax.swing.JButton button_ZAngle;
    private javax.swing.JCheckBox ch1;
    private javax.swing.JCheckBox ch10;
    private javax.swing.JCheckBox ch11_;
    private javax.swing.JCheckBox ch12;
    private javax.swing.JCheckBox ch13;
    private javax.swing.JCheckBox ch14;
    private javax.swing.JCheckBox ch15;
    private javax.swing.JCheckBox ch16;
    private javax.swing.JCheckBox ch2;
    private javax.swing.JCheckBox ch3;
    private javax.swing.JCheckBox ch4;
    private javax.swing.JCheckBox ch5;
    private javax.swing.JCheckBox ch6;
    private javax.swing.JCheckBox ch7;
    private javax.swing.JCheckBox ch8;
    private javax.swing.JCheckBox ch9;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JButton frontalLines17;
    private javax.swing.JButton frontalLines18;
    private javax.swing.JButton frontalLines19;
    private javax.swing.JButton frontalLines20;
    private javax.swing.JLabel imageLabel_Lateral;
    private javax.swing.JPanel imagePanel_Lateral;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lab1;
    private javax.swing.JLabel lab10;
    private javax.swing.JLabel lab11;
    private javax.swing.JLabel lab12;
    private javax.swing.JLabel lab13;
    private javax.swing.JLabel lab14;
    private javax.swing.JLabel lab15;
    private javax.swing.JLabel lab16;
    private javax.swing.JLabel lab2;
    private javax.swing.JLabel lab3;
    private javax.swing.JLabel lab4;
    private javax.swing.JLabel lab6;
    private javax.swing.JLabel lab7;
    private javax.swing.JLabel lab8;
    private javax.swing.JLabel lab9;
    private javax.swing.JTabbedPane lateralPane;
    private javax.swing.JLayeredPane layeredPanel;
    private javax.swing.JPanel maintPanel_Lateral;
    private javax.swing.JOptionPane optionPane;
    private javax.swing.JPanel patientInfoPanel_Lateral;
    private javax.swing.JTextField tx1;
    private javax.swing.JTextField tx2;
    private javax.swing.JTextField tx3;
    private javax.swing.JTextField tx4;
    private javax.swing.JTextField tx5;
    private javax.swing.JTextField tx6;
    private javax.swing.JTextField tx7;
    private javax.swing.JTextField tx8;
    private javax.swing.JTextField tx9;
    private javax.swing.JTextField txId_lateral;
    private javax.swing.JTextField txLastName_lateral;
    private javax.swing.JTextField txfirstName_lateral;
    private javax.swing.JInternalFrame welcome;
    // End of variables declaration//GEN-END:variables

    public Cloud getC() {
        return c;
    }

    public void setC(Cloud c) {
        this.c = c;
    }

}
